### PR TITLE
Testing

### PR DESCRIPTION
**Pull request by SigmaSam**
# Microverse Project #4 Building with Backgrounds and Gradients

 Old Apple website clone.

 # Microverse Project #4 04/25/2020.

 The objetive of this project was to recreate an old Apple website, setting background images as a base canvas and playing with gradiants options in CSS.

 ##   Features Added
 ###  Navigation Bar

 - It has a complete navigation bar as the example website.

 ### Grid background images
- A fixed and responsive grid layout as a background.

 ### Website Footer
  - Copy right
  - Policies Links
 - Links to the main sections of the website.

 ### Screenshorts

 screenshot

 ## Built With

 - HTML5,
 - CSS3

 ## Live Demo

 [Live Demo Link](https://rawcdn.githack.com/SigmaSam/Microverse-Project--4/3dc55c910c6a63f6868c225c5a33e318a0163a41/index.html)

 ## Getting Started

 **This is an example of how you may give instructions on setting up your project locally.**
 **Modify this file to match your project, remove sections that don't apply. For example: delete the testing section if the current project doesn't require testing.**

 To get a local copy up and running follow these simple example steps.

 ### Prerequisites
 - HTML5 semantic tags
 - CSS3
 - Git Workflow

 ### Setup
 - Clone the repo: ```https://github.com/SigmaSam/Microverse-Project--4.git```

 ### Install
 - Open index.html with the browser of your choice

 ## Author

 👤 **Author**

 - Github: [@githubhandle](https://github.com/SigmaSam)

 ## 🤝 Contributing

 Contributions, issues, and feature requests are welcome!

 Feel free to check the [issues page](issues/).

 ## Show your support

 Give a ⭐️ if you like this project!

 ## Acknowledgments

 - Hat tip to anyone who's code was used
 - Inspiration
 - etc

 ## 📝 License

 This project is [MIT](lic.url) licensed.

### CODE REVIEW

**Comment by adaorachi** [comment]
👋 Hi @SigmaSam,

Well done on the completion of the first draft of this project but sadly I cannot review it because your project DID NOT pass the code review validation. 
### **This Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready and have implemented the validation criteria below.**

- [ ] Your Pull Request should contain a meaningful title and a short summary, but what you have in your summary are contents meant for a README file. So update your Pull Request by adding a bullet list of the features you implemented in the project.

- [ ] Your commit messages are not very comprehensive and they do not show your progress on the project. Make sure you make commits as often as possible and also when you have implemented a feature and have done a significant change while working on your project.

See this [pathwright article](
https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/66243642/) for a more detailed instructions. Apply the rules there and make sure that your repo looks professional before submitting another code review.

The following is not a validation criterion, however your project will not be approved if it is not put in place.

- [ ] Make sure you set on Stickler for this project. The Linter validation messages/errors should be viewed in the Check tab of this project.

---

- [optional] And while you implement the above changes, I will also encourage you to edit the name of your feature branch to something related to the project like '**apple-clone**' instead of '**testing**' like you have it. The name is somewhat misleading.

Should you have any questions or need any help, please feel free to reach me on Slack with the username (@adaorachi).

Good luck on it and Happy Coding ☺️ 

**MaryAnn Chukwuka**

**Comment by SigmaSam** [comment]
Microverse Project #4 Building with Backgrounds and Gradients

Cloning and Old Apple website.

The objective of this project was to recreate an old Apple website, setting background images as a base canvas, and using the gradients options of CSS.

# Features Added

- ### Navigation Bar.
As the original website a full navigation bar responsive and adorned with a gradient design.
- ### Grid background images
A  responsive background designed with a grid to work in most resolutions.
- ### Website Footer
Copyright and Policies links, and a decorative "Change language" button.

**Review by addod19 — CHANGES_REQUESTED** [review]
## Status: Require changes :recycle: :traffic_light: 

Hi @SigmaSam, you did a great job with this project congratulations :+1: README looks good and the project looks great. However, we need to implement the comments below in order to proceed:
- The linter is not working correctly, let us fix that
- The copyright in the footer should be a link, kindly add it
g1
- Let us add links to each of the four elements 
```    
        <div class="c two"></div>
        <div class="c three"></div>
        <div class="c four"></div>
        <div class="c five"></div>
```
- Let us fix 1 warning returned by the w3validator
- Let us avoid the use of tag names and id for styling, let us intensively classes for styling
- Let us apply the DRY rule so we do not repeat code

Kindly implement these changes and submit another code review :+1: 
_Happy coding_ :man_technologist:
Daniel Larbi Addo on slack

**Comment by SigmaSam** [comment]
Added Linters to the repository.

**Comment by SigmaSam** [comment]
Added linters and passed all Checks, also fixed the reviewed issues.

**Comment by trekab** [comment]
# Project Approved! ok_hand
Well done, @SigmaSam! Let's get this merged. :tada:

_Goodluck with your next projects and happy coding!_

**Pull request merged**
